version: '3'

services:
  endproxy:
    image: motemere/testproject-endproxy:0.0.2-SNAPSHOT
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - OPENTRACING_JAEGER_UDP_SENDER_HOST=jaeger
      - OPENTRACING_JAEGER_UDP_SENDER_PORT=6831
      - TOPIC_NAME=testproject
      - ENTRYPOINT_URL=http://entrypoint:8083/api/v1/store/
    ports:
      - 8099:8099
    networks:
      - testproject
    depends_on:
      - kafka
      - middleproxy
