services:
  entrypoint:
    image: motemere/testproject-entrypoint:latest
    environment:
      - WEBSOCKET_URI=ws://middleproxy:8090/messages
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/testproject-db
      - SPRING_DATASOURCE_USERNAME=testproject
      - SPRING_DATASOURCE_PASSWORD=testproject
      - MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT=http://tempo:4318/v1/traces
      - MANAGEMENT_TRACING_SAMPLER_PROBABILITY=1.0
      - MANAGEMENT_OTLP_METRICS_EXPORT_ENABLED=false
    ports:
      - 8083:8083
    networks:
      - testproject
    depends_on:
      - db
