version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - testproject
      
  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports: 
      - "8081:8080"
    command: ["all"]
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    networks:
      - testproject
    depends_on:
      - jaeger
