version: '3'

services:
  middleproxy:
    image: motemere/testproject-middleproxy:latest
    environment:
      - KAFKA_BOOTSTRAPADDRESS=kafka:9092
      - OPENTRACING_JAEGER_UDP-SENDER_HOST=jaeger
      - OPENTRACING_JAEGER_UDP-SENDER_PORT=6831
      - MESSAGE_TOPIC_NAME=testproject
    ports:
      - 8090:8090
    networks:
      - testproject
    depends_on:
      - kafka
